# Generated by Django 5.2.17 on 2026-09-26 15:38

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code e.g. ENG', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, help_text='Searchable ID e.g. ACME-00001', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^ACME-\\d{5,}$', message='Must be ACME-xxxxx')])),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('full_name', models.CharField(db_index=True, editable=False, max_length=210)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('job_title', models.CharField(db_index=True, max_length=100)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('CONTRACT', 'Contract'), ('PART_TIME', 'Part-time'), ('INTERN', 'Intern')], default='FULL_TIME', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave')], db_index=True, default='ACTIVE', max_length=20)),
                ('date_of_joining', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='employees.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('house_rent_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='House Allowance (HRA)')),
                ('dearness_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Dearness Allowance (DA)')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Transport Allowance (TA)')),
                ('telephone_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='PF Deduction')),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('net_in_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('total_compensation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('effective_from', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Salary Structure',
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Null = no upper bound', max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage e.g. 10.00 for 10%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['country', 'lower_limit'],
                'indexes': [models.Index(fields=['country', 'lower_limit'], name='employees_t_country_18d70b_idx')],
                'constraints': [models.UniqueConstraint(fields=('country', 'lower_limit'), name='uniq_tax_bracket_country_lower')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['country', 'job_title'], name='employees_e_country_c7cff2_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department', 'country'], name='employees_e_departm_b121b2_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['full_name'], name='employees_e_full_na_997ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='employees_e_status_61c2f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='employee_email_not_empty'),
        ),
    ]
