# Generated by Django 5.2.17 on 2026-09-27 15:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_basic', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('new_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('old_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'created_at'], name='employees_s_employe_56a9e3_idx')],
            },
        ),
    ]
